// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Distributed File Storage API",
	Description:      "This is a sample server for a file storage API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

// docTemplate defines the Swagger documentation format
const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "schemes": {{ marshal .Schemes }},
    "paths": {
        "/upload": {
            "post": {
                "tags": ["files"],
                "summary": "Upload File",
                "description": "Upload a file and split it into multiple parts.",
                "parameters": [{
                    "name": "file",
                    "in": "formData",
                    "required": true,
                    "type": "file"
                }],
                "responses": {
                    "200": {
                        "description": "File uploaded successfully",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "file_id": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "No file is received"
                    },
                    "500": {
                        "description": "File splitting failed"
                    }
                }
            }
        }
    }
}`

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
