version: "3.8"

services:
  app:
    build: .
    container_name: distributed-file-storage-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/files

  db:
    image: postgres:16
    container_name: distributed-file-storage-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: files
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
